apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  volumes:
    - name: html-volume
      emptyDir: {}

  initContainers:
    - name: setup
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: ["mkdir -p /usr/share/nginx/html && echo 'Initial content' > /usr/share/nginx/html/index.html"]
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html

  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html

    - name: time-updater
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args: ["while true; do date > /usr/share/nginx/html/index.html; sleep 10; done"]
      volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html