apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: default
  labels: 
    app.kubernetes.io/name: demo
spec:
  containers:
    - name: nginx-box
      image: nginx:latest
      command: ["/bin/sh", "-c"]
      args: 
        - |
          nginx -g "daemon off;" &  
          sleep infinity       
      ports:
        - containerPort: 80
      livenessProbe:
        exec: 
          command:
            - "/bin/sh"
            - "-c"
            - "true"
        initialDelaySeconds: 5
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5

