apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: shared-node-app 
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - shared-node-app
        topologyKey: kubernetes.io/hostname
  containers:
  - name: nginx
    image: nginx