apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: shared-node-app 
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - shared-node-app
        topologyKey: kubernetes.io/hostname
  containers:
  - name: redis
    image: redis