apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  # namespace: demo
  labels:
    name: demo
spec:
  restartPolicy: Never
  containers:
    - name: demo-container
      image: busybox:latest
      command: ["sh", "-c", "sleep 3600"]

